/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Welcome */

#ifndef _Included_Welcome
#define _Included_Welcome
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
